modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
version="${mod_version}"
displayName="${mod_name}"
modId="${mod_id}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/SirCesarium/Beacon-Core" #optional
logoFile="beacon_core.png"
#credits="" #optional
authors="SirCesarium"
description='''
Annotation-based registry engine for NeoForge.
'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
